### ISSUE TITLE
Returning wrong type in InstallationTemplate.fromJson(stream)

### ISSUE THREAD

**Issue by aziel** [Azure/azure-notificationhubs-java-backend#16]
https://github.com/Azure/azure-notificationhubs-java-backend/blob/master/NotificationHubs/src/com/windowsazure/messaging/InstallationTemplate.java#L80

Currently returning Installation in this method, should be InstallationTemplate

**Comment by mpodwysocki** [comment]
Fixed as per:

```java
    public static InstallationTemplate fromJson(String json) {
        return new Gson().fromJson(json, InstallationTemplate.class);
    }
```
