### ISSUE TITLE
Value of ConnectionString To Instantiate NamespaceManager

### ISSUE THREAD

**Issue by lasarvit** [Azure/azure-notificationhubs-java-backend#18]
NamespaceManager requires "connection string". What should be the value of it.
Tried below values(1&2) but got "java.lang.RuntimeException: Error: HTTP/1.1 401 Unauthorized - 401InvalidSignature: The token has an invalid signature..TrackingId:99ed6a26-42fa-471c-bfab-b7a21fa7d834_G0,TimeStamp:5/23/2016 5:36:33 PM"

1.DefaultListenSharedAccessSignature:
Endpoint=sb://{XXXXX}.servicebus.windows.net/;SharedAccessKeyName=DefaultListenSharedAccessSignature;SharedAccessKey=KKKKKKKKKKKKKKKKKKKKKKKKK
2.DefaultFullSharedAccessSignature:
Endpoint=sb://{XXXXX}.servicebus.windows.net/;SharedAccessKeyName=DefaultFullSharedAccessSignature;SharedAccessKey=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by mpodwysocki** [comment]
To use the NamespaceManager, you need to copy the value of the `DefaultFullSharedAccessSignature` connection string.
