### ISSUE TITLE
method to get registration by Baidu ChannelId

### ISSUE THREAD

**Issue by allenhula** [Azure/azure-notificationhubs-java-backend#19]
This existing method getRegistrationsByChannelAsync internal is sending query with filter "ChannelUri eq", seems only supports for MPNS, not for APNS, GCM and Baidu.
I can follow [REST API](https://msdn.microsoft.com/en-us/library/azure/dn223271.aspx) to implement corresponding methods for APNS and GCM, but no luck on Baidu with below queries. Does it not support? Or is my filter condition wrong?
• https://{namespace}.servicebus.windows.net/{NotificationHub}/registrations/?$filter= BaiduChannelId eq ‘{BaiduChannelId}’&api-version=2015-01
• https://{namespace}.servicebus.windows.net/{NotificationHub}/registrations/?$filter= Channel eq ‘{BaiduUserId-BaiduChannelId}’&api-version=2015-01
• https://{namespace}.servicebus.windows.net/{NotificationHub}/registrations/?$filter= (BaiduChannelId eq ‘{BaiduChannelId}’) and (BaiduUserId eq ‘{BaiduUserId}’)&api-version=2015-01

**Comment by allenhula** [comment]
found the channel name for Baidu. It is BaiduUserId-BaiduChannelId.

**Comment by mpodwysocki** [comment]
@allenhula correct, the channel is as you stated.  Will add `pnsHandle` to the registration class to clarify.
