### ISSUE TITLE
Issues found when notification application is behind proxy

### ISSUE THREAD

**Issue by lolocn** [Azure/azure-notificationhubs-java-backend#26]
My notification application is deployed behind a proxy, I have to config `http.proxyHost` or `https.proxyHost` to access Azure NotificationHub. However I notice the `HttpAsyncClients` created in the  `HttpClientManager` is a default one and it will never use system properties.
```
public class HttpClientManager {
	private static CloseableHttpAsyncClient httpAsyncClient;
	
	public static CloseableHttpAsyncClient getHttpAsyncClient() {
		if(httpAsyncClient == null) {
			synchronized(HttpClientManager.class) {
				if(httpAsyncClient == null) {
					CloseableHttpAsyncClient client = HttpAsyncClients.createDefault();
					client.start();
```

To use system properties configured in jvm, I have modify the client creation method to
```
CloseableHttpAsyncClient client = HttpAsyncClients.createSystem();
```
I looked into `HttpAsyncClients` source code, it is clear the difference is whether useSystemProperties
```
    /**
     * Creates {@link CloseableHttpAsyncClient} instance with default
     * configuration.
     */
    public static CloseableHttpAsyncClient createDefault() {
        return HttpAsyncClientBuilder.create().build();
    }

    /**
     * Creates {@link CloseableHttpAsyncClient} instance with default
     * configuration based on ssytem properties.
     */
    public static CloseableHttpAsyncClient createSystem() {
        return HttpAsyncClientBuilder.create().useSystemProperties().build();
```

Hope this issue can be fixed.

**Comment by jmgrozas** [comment]
I have the same problem ... My work around is:

´´´java

	/** Nme of system property to activate httpAsyncClient create with system properties */
	private static final String SYSTEM_HTTP_CLIENT_CREATE = "http_client_type";

	private static CloseableHttpAsyncClient httpAsyncClient;

	public static CloseableHttpAsyncClient getHttpAsyncClient() {
		if(httpAsyncClient == null) {
			synchronized(HttpClientManager.class) {
				if(httpAsyncClient == null) {
					/* Create http client by type */
					HttpClientType clientType = HttpClientType.valueOf(System.getProperty(SYSTEM_HTTP_CLIENT_CREATE));
					CloseableHttpAsyncClient client = HttpAsyncClients.createDefault();
					if (HttpClientType.MINIMAL.equals(clientType)){
						client = HttpAsyncClients.createMinimal();
					} else if (HttpClientType.SYSTEM.equals(clientType)){
						client = HttpAsyncClients.createSystem();
					}else {
						client = HttpAsyncClients.createDefault();
					}
					client.start();
					httpAsyncClient = client;	    	   
				}
			}
		}
		  
		return httpAsyncClient;
	}

	public static void setHttpAsyncClient(CloseableHttpAsyncClient httpAsyncClient) {
		synchronized (HttpClientManager.class) {
			if (HttpClientManager.httpAsyncClient == null) {
				HttpClientManager.httpAsyncClient = httpAsyncClient;
			} else {
				throw new RuntimeException("HttpAsyncClient was already set before or default one is being used.");
			}
		}
	}

	/**
	 * Enum represent httpClients
	 * 
	 * @author manuel
	 *
	 */
	private enum HttpClientType {
		DEFAULT, MINIMAL, SYSTEM;
	}

´´´
I hope that Azure will change strategy of implementation

**Comment by nvguerreiro** [comment]
Hi, I managed to use my corporate proxy with NTLM integrated authentication (no username and password specified) on my Windows 8 workstation, without changing this library's source code.

Here's my code:

`import com.windowsazure.messaging.*;

import java.util.concurrent.Future;

import org.apache.http.auth.AuthSchemeProvider;
import org.apache.http.client.CredentialsProvider;
import org.apache.http.client.config.AuthSchemes;
import org.apache.http.concurrent.FutureCallback;
import org.apache.http.config.Registry;
import org.apache.http.config.RegistryBuilder;
import org.apache.http.HttpHost;
import org.apache.http.impl.auth.BasicSchemeFactory;
import org.apache.http.impl.auth.DigestSchemeFactory;
import org.apache.http.impl.auth.win.WindowsCredentialsProvider;
import org.apache.http.impl.auth.win.WindowsNTLMSchemeFactory;
import org.apache.http.impl.auth.win.WindowsNegotiateSchemeFactory;
import org.apache.http.impl.client.SystemDefaultCredentialsProvider;
import org.apache.http.impl.client.WinHttpClients;
import org.apache.http.impl.nio.client.CloseableHttpAsyncClient;
import org.apache.http.impl.nio.client.HttpAsyncClientBuilder;

public class Test9 {
    private static HttpAsyncClientBuilder createAsyncBuilderWithProxy(String proxyHost, int proxyPort) {
        if (WinHttpClients.isWinAuthAvailable()) {
            final Registry<AuthSchemeProvider> authSchemeRegistry = RegistryBuilder.<AuthSchemeProvider>create()
                    .register(AuthSchemes.BASIC, new BasicSchemeFactory())
                    .register(AuthSchemes.DIGEST, new DigestSchemeFactory())
                    .register(AuthSchemes.NTLM, new WindowsNTLMSchemeFactory(null))
                    .register(AuthSchemes.SPNEGO, new WindowsNegotiateSchemeFactory(null))
                    .build();
            final CredentialsProvider credsProvider = new WindowsCredentialsProvider(new SystemDefaultCredentialsProvider());
            return HttpAsyncClientBuilder.create()
                    .setDefaultCredentialsProvider(credsProvider)
                    .setDefaultAuthSchemeRegistry(authSchemeRegistry)
					.setProxy(new HttpHost(proxyHost, proxyPort));
        } else {
            return HttpAsyncClientBuilder.create().setProxy(new HttpHost(proxyHost, proxyPort));
        }
    }

	public static void main(String[] args) throws Exception {
		if(args.length < 4) {
			System.err.println("syntax: java Test9 <hub connection string> <hub name> <push notification address> <push message>");
		} else {
			String hubConnectionString = args[0];
			String hubName = args[1];
			String pushNotificationAddress = args[2];
			String pushMessage = args[3];

			CloseableHttpAsyncClient httpClient = createAsyncBuilderWithProxy("proxy.corporate.com", 8080).build();
			httpClient.start();
			HttpClientManager.setHttpAsyncClient(httpClient);
			
			NotificationHub hub = new NotificationHub(hubConnectionString, hubName);

			Notification notification = Notification.createGcmNotifiation(pushMessage);
            
			hub.sendDirectNotification(notification, pushNotificationAddress);
			
			System.out.println("Notification sent!");
			
			httpClient.close();
		}
	}
}`

**Comment by paulrho** [comment]
This would still be worth building into the library, an option to use system proxy defaults or some other (standard) way to specify a proxy.  Currently trying to "add" a proxy to our existing app (without changing code) - and realise now it is not possible.
