### ISSUE TITLE
Not support to submit registration on Baidu through Installation API

### ISSUE THREAD

**Issue by hfmj** [Azure/azure-notificationhubs-java-backend#28]
According to the source code of enum NotificationPlatform:

public enum NotificationPlatform {
    @SerializedName("wns")
    Wns,
    @SerializedName("apns")
    Apns,
    @SerializedName("mpns")
    Mpns,
    @SerializedName("gcm")
    Gcm,
    @SerializedName("adm")
    Adm;

    private NotificationPlatform() {
    }
}

I do not think there is an item for Baidu channel.
so my question is that, if we try to pushing notification through Baidu, what should we do by Installation API? Thanks.

**Comment by mpodwysocki** [comment]
Closed as per #91
