### ISSUE TITLE
Misspelled method name

### ISSUE THREAD

**Issue by y-luis** [Azure/azure-notificationhubs-java-backend#29]
The name of the method to set up a native notification for GCM is misspelled:

`createGcmNotifiation`

note the missing C letter!

Even more is incorrectly used/correctly spelled at [https://docs.microsoft.com/en-us/azure/notification-hubs/notification-hubs-java-push-notification-tutorial](url)

**Comment by mpodwysocki** [comment]
@y-luis fixed and deprecated old methods
