### ISSUE TITLE
Apple device token (64 characters) is not accepted by ANH

### ISSUE THREAD

**Issue by wouterapg** [Azure/azure-notificationhubs-java-backend#34]
I tried, using this sdk, to register, for example, the following devicetoken (optained via device):
**96d6bb5d 412881d3 0046f5bf 5616bead df6aa4ab e57987bc cc4b5c23 209dbb0c**

I tried the following things:
- as is; with spaces
- remove spaces
- dashes instead of spaces

But they all give next error in return:
com.windowsazure.messaging.NotificationHubsException: Error: HTTP/1.1 400 Bad Request - <Error><Code>400</Code><Detail>**One or more characters in device token is not a hexadecimal digit**..TrackingId:c9b0fa60-c8e7-4281-9f6c-efd7ed2b19a2_G18,TimeStamp:6/19/2018 11:57:33 AM</Detail></Error>

it seems to only accept 32 characters hexidecimal string (only first 32 characters works fine for the registration: **96d6bb5d412881d30046f5bf5616bead** )

I added the library via Maven:
			groupId: com.windowsazure
			artifactId: NotificationHubs
			version: 0.0.5

In com.windowsazure.messaging.NotificationHub next version is mentioned:
APIVERSION = "?api-version=2015-04"

Is this version too old?
What am I doing wrong?
Is this library outdated/depricated?
Is there an other/ better way to make this work?

thanks in advance for your response

**Comment by wouterapg** [comment]
problem seemes to be solved.
Solution now, with Apple device tokens, is to remove all spaces when registring the device in Azure:

- from

 APNS: 96d6bb5d 412881d3 0046f5bf 5616bead df6aa4ab e57987bc cc4b5c23 209dbb0c
to Azure: 96d6bb5d412881d30046f5bf5616beaddf6aa4abe57987bccc4b5c23209dbb0c

**Comment by mpodwysocki** [comment]
Closing as per answer, remove all whitespace for the APNS Device Token.
