### ISSUE TITLE
Java SDK deleteRegistration returning 400 Bad Request for FCM devices

### ISSUE THREAD

**Issue by marcelogiarola-zz** [Azure/azure-notificationhubs-java-backend#42]
I'm not been able to unregister fcm devices:

- Registration:
`registration = new FcmRegistration(command.getDeviceId());
NotificationHub hub = new NotificationHub(connectionString, notificationHubPath);
registration = hub.createRegistration(registration);`

- Unregistration:
`NotificationHub hub = new NotificationHub(connectionString, notificationHubPath);
final CollectionResult result = hub.getRegistrationsByTag(tag);
                            final List<Registration> registrations = result.getRegistrations();
                            registrations.stream().forEach(registration -> {
                                       hub.deleteRegistration(registration.getRegistrationId());
                            }`

The unregistration process return a response like this:

com.windowsazure.messaging.NotificationHubsException: Error: HTTP/1.1 400 Bad Request - <Error><Code>400</Code><Detail>The notification hub was created with an older API version. Either re-create the notification hub or use an older API version, 2017-11, to access it.TrackingId:7c0e379b-b80e-4eb9-bb45-d808aa004908_G5,TimeStamp:2/11/2019 4:23:02 PM</Detail></Error>

Could someone point me what I'm doing wrong or if there is an issue with the API?

**Comment by mpodwysocki** [comment]
@marcelogiarola-zz It seems that this hub was created a long time ago.  Try an update on the hub through the management APIs to ensure that it will be using the latest API version.  Open the issue again if this issue persists.
