### ISSUE TITLE
Push Notifications do not work for iOS 13.x

### ISSUE THREAD

**Issue by avramanaareddy** [Azure/azure-notificationhubs-java-backend#48]
I am working on the background application to send notification to apple devices that are upgraded to the iOS version 13.1.2.
The notifications are perfectly sent to iOS 12 version but not to iOS version 13.
I have added the following statements as per the suggestions given in the stackoverflow website
notification.headers.put("apns-push-type", "alert");
notification.headers.put("apns-priority", "5");
Can you please provide the fix for this?

We have used all the classes that you provided in this github.
https://github.com/Azure/azure-notificationhubs-java-backend

The backend Java application, which we wrote the code for sending push notifications. It is sending the push notifications perfectly to iOS 12.x version devices, but not to the iOS 13.x

**Comment by brannon** [comment]
@avramanaareddy can you provide a link to the StackOverflow post?

Have you tried setting the `apns-priority` value to `10` ? As per Apple documentation, a value of `10` is appropriate for "alert" notifications. Notifications sent with a value of `5` are subject to batching, throttling, or being dropped.

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns

Your code snippet is referencing a private member of the `Notification` class:
```
notification.headers.put(...);
```

Are you instead using the following?
```
notification.getHeaders().put(...);
```

**Comment by avramanaareddy** [comment]
Let me try

**Comment by avramanaareddy** [comment]
> @avramanaareddy can you provide a link to the StackOverflow post?
> 
> Have you tried setting the `apns-priority` value to `10` ? As per Apple documentation, a value of `10` is appropriate for "alert" notifications. Notifications sent with a value of `5` are subject to batching, throttling, or being dropped.
> 
> https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/sending_notification_requests_to_apns
> 
> Your code snippet is referencing a private member of the `Notification` class:
> 
> ```
> notification.headers.put(...);
> ```
> 
> Are you instead using the following?
> 
> ```
> notification.getHeaders().put(...);
> ```
Yes, I am doing exactly like above, what you mentioned

notification.headers.put("ServiceBusNotification-Apns-Expiry", expiryString);
            notification.headers.put("apns-push-type", "alert");
            notification.headers.put("apns-priority", "10");
I have printed the same in the log before sending the push notification also.
{apns-push-type=alert, ServiceBusNotification-Apns-Expiry=10/23/2019 03:35:56, ServiceBusNotification-Format=apple, apns-priority=10}


It gives tracking id as 0d104017-4d70-44d3-86c6-ee9581157bf0
but I don't get any push notification, i have iOS 13.x apple device.

**Comment by avramanaareddy** [comment]
0d104017-4d70-44d3-86c6-ee9581157bf0

**Comment by avramanaareddy** [comment]
Yes, I am doing exactly like above, what you mentioned

notification.headers.put("ServiceBusNotification-Apns-Expiry", expiryString);
notification.headers.put("apns-push-type", "alert");
notification.headers.put("apns-priority", "10");
I have printed the same in the log before sending the push notification also.
{apns-push-type=alert, ServiceBusNotification-Apns-Expiry=10/23/2019 03:35:56, ServiceBusNotification-Format=apple, apns-priority=10}

It gives tracking id as 0d104017-4d70-44d3-86c6-ee9581157bf0
but I don't get any push notification, i have iOS 13.x apple device.

**Comment by omerh86** [comment]
Is there any update?,  I'm having same issue
