### ISSUE TITLE
NotificationHub.createOrUpdateInstallation got Internal server error.

### ISSUE THREAD

**Issue by m-moris** [Azure/azure-notificationhubs-java-backend#57]
I execute the following code, I got an internal server error.
I debugged the Java SDK and compared it with the .NET SDK and found the cause.

```java
    Installation installation = new Installation(id, NotificationPlatform.Fcm, deviceToken);
    hub.createOrUpdateInstallation(installation);
```

The direct cause is passing the FCM as the second argument. FCM is not allowed on the REST API. So I changed FCM to GCM, it works properly.

[Create or overwrite an installation | Microsoft Docs](https://docs.microsoft.com/en-us/rest/api/notificationhubs/create-overwrite-installation)

> Platform Can be {APNS, WNS, MPNS, ADM, GCM}.

In .NET SDK, I set FCM in platform property ,  it is internally converted to GCM and posted to REST API. So it works correctly.
See https://github.com/Azure/azure-notificationhubs-dotnet/blob/master/src/Microsoft.Azure.NotificationHubs/NotificationPlatform.cs#L45

```cs
    var installation = new Installation();
    installation.PushChannel = deviceToken;
    installation.InstallationId = id;
    installation.Platform = NotificationPlatform.Fcm;
    client.CreateOrUpdateInstallation(installation);
```

I think the behavior of the Java SDK is unkind and confusing, so I think it should either be converted internally or raise an exception when FCM is specified.

**Comment by marstr** [comment]
This is great feedback, thanks for this @m-moris.

**Comment by mpodwysocki** [comment]
@m-moris it's a bug on our side.  We do not officially support FCM natively and instead support FCM legacy.  In our next release, we will update this so that we support `Gcm` and `FcmLegacy` and will remove `Fcm`.
