### ISSUE TITLE
Bintray and JCenter Decommissioning

### ISSUE THREAD

**Issue by marstr** [Azure/azure-notificationhubs-java-backend#82]
JFrog has announced that [they are shutting down Bintray](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). This includes JCenter, and imposes a change to they way customers will take a dependency on this package. At the time of writing, we are not yet prepared to announce our migration plans. Stay tuned for more information.

**Comment by m-moris** [comment]
I concerned this matter. I would like the Notification Hub SDK will be deployed to the Maven Central Repository like the other Azure SDKs. The version of the SDK is currently deployed is too old.

https://search.maven.org/search?q=a:NotificationHubs

**Comment by marstr** [comment]
Howdy @m-moris, thanks for inquiring.

As you've guessed, we are planning on moving our SDKs to Maven Central. Expect the packages to be available there in the next few weeks, well ahead of the May shut-off.

**Comment by mpodwysocki** [comment]
Closing as per now available on SonaType for [Notification-Hubs-Java-sdk](https://search.maven.org/artifact/com.windowsazure/Notification-Hubs-java-sdk)
