### ISSUE TITLE
createWindowsNotification doesn't add X-WNS-Type header when the message body has xml prolog

### ISSUE THREAD

**Issue by daatlk** [Azure/azure-notificationhubs-java-backend#86]
This method has been changed recently to replace contains checks with regex.

However a regex like **"^<toast[\\s\\S]*>[\\s\\S]+</toast>$"** does not match when the message body has a xml prolog. Also noted this regex seems correct in other languages. 

ex message body from test send in Azure portal
```

<?xml version="1.0" encoding="utf-8"?>
<toast>
<visual><binding template="ToastText01">
<text id="1">Test message</text>
</binding>
</visual>
</toast>
```
Tried "\\s*<toast[\\s\\S]*>[\\s\\S]+</toast>$" and it seems to work with java regex.

**Comment by mpodwysocki** [comment]
Closed as per #90
